version: '3.8'

services:
  # Web service - serves the leaderboard website and handles webhooks
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: tagpro-web
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl/certs
      - ./nginx/www:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  # Bot service - manages TagPro games via Discord
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: tagpro-bot
    volumes:
      - ./data:/app/data
      - ./pythonScripts/bot:/app/bot
    restart: always
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python /app/bot/leader.py
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: tagpro-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - web
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge